services:
    datasets.twig.datasets_extension:
        class: Damis\DatasetsBundle\Twig\DatasetsExtension
        tags:
            - { name: twig.extension }
    midas_service:
        class:  Damis\DatasetsBundle\Controller\MidasController
        arguments:
            session: @session
            container: @service_container