services:
  experiment:
      class: Damis\ExperimentBundle\Helpers\Experiment
      arguments: [@doctrine.orm.entity_manager]
  grid.column.status:
      class: Damis\ExperimentBundle\Grid\Column\StatusColumn
      public: false
      tags:
          -  { name: grid.column.extension }